version: '3'

services:
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=airportaimaster
      - MONGO_INITDB_ROOT_PASSWORD=airportaipassword
      - MONGO_INITDB_DATABASE=airportai
    ports:
      - "27017:27017"
  airportai-exercise:
    platform: linux/amd64
    depends_on:
      - mongodb
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        - API_PORT=${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - /app/node_modules
      - .:/app